name: Clang-Format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jidicula/clang-format-action@v3.4.0
        with:
          clang-format-version: '11'
