name: Build
on: [push, pull_request]
jobs:
  build_wheels:
    name: Wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      CIBW_ARCHS: "auto64"
      CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
      CIBW_ENVIRONMENT_LINUX: "CC=clang CXX=clang++"
      CIBW_TEST_COMMAND: "pytest {package}"
      CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: boost_root
          key: ${{ runner.os }}-boost-1.74.0-pic
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true' && matrix.os == 'ubuntu-latest'
        env:
          CC: clang
          CXX: clang++
        run: external/libSMCE/ci/build-static-boost.sh 1.74.0
      - name: Install Boost
        if: matrix.os == 'macOS-latest'
        run: brew install boost
      - name: Install Boost
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: external\libSMCE\ci\install-boost.ps1 '14.2' '1.77.0' '1_77_0'
      - uses: actions/setup-python@v2
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
