name: Build
on: [push, pull_request]
jobs:
  build_wheels:
    name: Wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      CIBW_ARCHS: "auto64"
      CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
      CIBW_BEFORE_ALL_LINUX: >
        yum install -y openssl-static ||
        apt-get install -y libssl-dev ||
        apk -U add openssl-libs-static
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
      CIBW_TEST_REQUIRES: "pytest pytest-asyncio"
      CIBW_TEST_COMMAND: "pytest {project}/test"
      CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        if: matrix.os == 'macOS-latest'
        run: |
          brew install openssl@3
          curl -sL https://github.com/AeroStun/brew-lipo/raw/master/brew-lipo.sh | bash -s openssl@3
          echo "export OPENSSL_ROOT_DIR=\"$(brew --prefix openssl@3)\"" >> /Users/runner/.bash_profile
      - name: Install deps
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install openssl
      - uses: actions/setup-python@v2
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
